joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  
  left_wheel: base_to_roda_esquerda
  right_wheel: base_to_roda_direita
  
  wheel_separation: 0.12172
  wheel_radius: 0.02614
  
  cmd_vel_timeout: 0.25
  enable_odom_tf: true
  
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  
  base_frame_id: base_link


# Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1  # m/s
      has_acceleration_limits: true
      max_acceleration       : 3   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 3   # rad/s^2
